import {Book} from './app/shared/models/books';
import {Tag} from './app/shared/models/tags';
export const sample_book: Book[]=[
    {
        id:'1',
        name:'Knox',
        author:'fevered',
        price:111111,
        favorite:false,
        origins:['India','Asia'],
        stars:5,
        imageUrl:'https://i.pinimg.com/474x/67/5f/e9/675fe9f0bafe673b851174bd235e4a54.jpg',
        tags:['Fiction','Pizza','Lunch'],
    },
    {
        id:'2',
        name:'Consider Me',
        author:'Becka Meck',
        price:11111,
        favorite:false,
        origins:['India','Asia'],
        stars:5,
        imageUrl:'https://i.pinimg.com/474x/96/d5/cb/96d5cb5ed865e92796cf813afaf6d274.jpg',
        tags:['FastFood','Pizza','Lunch'],
    },
    {
        id:'3',
        name:'Consider Me',
        author:'Becka Meck',
        price:11111,
        favorite:false,
        origins:['India','Asia'],
        stars:5,
        imageUrl:'https://i.pinimg.com/564x/f7/13/65/f7136518ba39e91a4119d0117c7d6baa.jpg',
        tags:['FastFood','Pizza','Lunch'],
    },
    {
        id:'4',
        name:'Consider Me',
        author:'Becka Meck',
        price:11111,
        favorite:false,
        origins:['India','Asia'],
        stars:5,
        imageUrl:'https://i.pinimg.com/564x/cb/96/2d/cb962df0b1530a068bc997141be1b12c.jpg',
        tags:['FastFood','Pizza','Lunch'],
    },
    {
        id:'2',
        name:'Consider Me',
        author:'Becka Meck',
        price:11111,
        favorite:false,
        origins:['India','Asia'],
        stars:5,
        imageUrl:'https://i.pinimg.com/474x/96/d5/cb/96d5cb5ed865e92796cf813afaf6d274.jpg',
        tags:['FastFood','Pizza','Lunch'],
    },
    {
        id:'2',
        name:'Consider Me',
        author:'Becka Meck',
        price:11111,
        favorite:false,
        origins:['India','Asia'],
        stars:5,
        imageUrl:'https://i.pinimg.com/474x/96/d5/cb/96d5cb5ed865e92796cf813afaf6d274.jpg',
        tags:['FastFood','Pizza','Lunch'],
    },
    {
        id:'2',
        name:'Consider Me',
        author:'Becka Meck',
        price:11111,
        favorite:false,
        origins:['India','Asia'],
        stars:5,
        imageUrl:'https://i.pinimg.com/474x/96/d5/cb/96d5cb5ed865e92796cf813afaf6d274.jpg',
        tags:['FastFood','Pizza','Lunch'],
    },
    {
        id:'2',
        name:'Consider Me',
        author:'Becka Meck',
        price:11111,
        favorite:false,
        origins:['India','Asia'],
        stars:5,
        imageUrl:'https://i.pinimg.com/474x/96/d5/cb/96d5cb5ed865e92796cf813afaf6d274.jpg',
        tags:['FastFood','Pizza','Lunch'],
    },
    {
        id:'2',
        name:'Consider Me',
        author:'Becka Meck',
        price:11111,
        favorite:false,
        origins:['India','Asia'],
        stars:5,
        imageUrl:'https://i.pinimg.com/474x/96/d5/cb/96d5cb5ed865e92796cf813afaf6d274.jpg',
        tags:['FastFood','Pizza','Lunch'],
    },
    {
        id:'2',
        name:'Consider Me',
        author:'Becka Meck',
        price:11111,
        favorite:false,
        origins:['India','Asia'],
        stars:5,
        imageUrl:'https://i.pinimg.com/474x/96/d5/cb/96d5cb5ed865e92796cf813afaf6d274.jpg',
        tags:['FastFood','Pizza','Lunch'],
    },
    {
        id:'2',
        name:'Consider Me',
        author:'Becka Meck',
        price:11111,
        favorite:false,
        origins:['India','Asia'],
        stars:5,
        imageUrl:'https://i.pinimg.com/474x/96/d5/cb/96d5cb5ed865e92796cf813afaf6d274.jpg',
        tags:['FastFood','Pizza','Lunch'],
    }

]

export const sample_tags:Tag[]=[
    {name:'All', count:6},
    {name:'Fiction', count:6},
    {name:'Non-Fiction', count:6},
    {name:'Physocology', count:6},
    {name:'Thriller', count:6},
    {name:'Romance', count:6},
    {name:'Contemprary', count:6},
    {name:'Biopic', count:6},
    {name:'Horror', count:6},
]